### ISSUE TITLE
DIYing a unify receiver

### ISSUE THREAD

**Issue by WanderingNullPtr** [bilogic/logitech-unifying-device#4]
Hi,
Thanks for your efforts into this. I am thinking about implementing a Unify receiver using a nrf24 module. Since I dont have one its really hard for me to reverse engineer it. Can I pick your brains to how you went about doing one? Thanks a lot for any inputs you might have.

**Comment by bilogic** [comment]
It boils down to understanding protocol and its the packets. I would start with https://github.com/bilogic/logitech-unifying-device/blob/master/notes.md as the source of truth and go through the code to pick it apart.

Receivers are pretty cheap and widely available. It might be easier to interface its USB and write code there rather than hack your way through this.

Do close this issue when you have no further questions. Thank you.

**Comment by WanderingNullPtr** [comment]
Thanks for the reply, the main reason I am considering this is the price of unifying dongles here are 3-4 times the normal price and that itself is closer in price to the mouse I have. It is primarily used as a bluetooth mouse but I wanted to see the latency improvements on unifying receiver.

**Comment by bilogic** [comment]
Hmm, I can understand if it is a hobby/interest, but I don't think 3-4 times the normal price will cost more than the amount of time you will be spending on this.

**Comment by WanderingNullPtr** [comment]
You are right, diy-ing the receiver is hard enough and without an original for reference is even harder. So I started searching a bit more thoroughly which led me to a whole market selling loose un packaged unifying dongles (which I suspect comes from units with defective keyboards/mice, mine seemed to come paired to a K230 keyboard). I still plan to pursue this project, hoping it to be a bit less of shooting in the dark.

P.S. The dongle also cost like a third of its MRP!

**Comment by bilogic** [comment]
Well, all the best!
